services:
  db:
    container_name: postgres_container
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      # This folder is ONLY for Postgres internal files (keep it empty at start!)
      - ./postgresql:/var/lib/postgresql/data
      # This folder is for the CSV files
      - ./data:/mnt/csv_data
    ports:
      - "5433:5432"  # host_port:container_port
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:9.7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
