name: plotlyenv
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - ca-certificates=2024.11.26=haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.9.20=py39hd8ed1ab_1
  - debugpy=1.8.9=py39ha51f57c_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.18.1=pyh7428d3b_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - krb5=1.21.3=hdf4eb48_0
  - libsodium=1.0.20=hc70643c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.4.0=h2466b09_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=py39haa95532_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.0=py39ha55e580_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - python=3.9.20=h8205438_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=2_cp39
  - pywin32=307=py39ha51f57c_3
  - pyzmq=26.2.0=py39h03e5c00_3
  - setuptools=75.1.0=py39haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tornado=6.4.2=py39ha55e580_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.44.0=py39haa95532_0
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - pip:
      - blinker==1.9.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==2.8.1
      - dash-bootstrap-components==1.3.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-molstar==1.1.1
      - dash-table==5.0.0
      - flask==3.1.0
      - fonttools==4.55.0
      - greenlet==3.1.1
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - markupsafe==3.0.2
      - matplotlib==3.9.3
      - numpy==2.0.2
      - pandas==2.2.3
      - pillow==11.0.0
      - plotly==5.13.0
      - psycopg2==2.9.10
      - pyparsing==3.2.0
      - pytz==2024.2
      - six==1.16.0
      - sqlalchemy==2.0.36
      - tenacity==9.0.0
      - tzdata==2024.2
      - werkzeug==3.1.3
prefix: C:\Users\Admin\miniconda3\envs\plotlyenv
